# Generated by Django 6.0.2 on 2026-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('curriculo', models.FileField(upload_to='curriculos/')),
                ('formacao', models.TextField()),
                ('instituicao_ensino', models.CharField(max_length=300)),
                ('ano_concluido', models.IntegerField()),
                ('experiencia_anos', models.IntegerField(help_text='Anos de experiência profissional')),
                ('cargo_atual', models.CharField(blank=True, help_text='Cargo atual ou Último cargo ocupado', max_length=200)),
                ('empresa_atual', models.CharField(blank=True, help_text='Empresa atual ou última empresa que trabalhou', max_length=200)),
                ('salario_atual', models.DecimalField(blank=True, decimal_places=2, help_text='Salario atual ou ultimo salario', max_digits=15, null=True)),
                ('resumo_profissional', models.TextField()),
                ('vaga_interesse', models.CharField(max_length=200)),
                ('pretensao_salarial', models.DecimalField(decimal_places=2, help_text='Expectativa salarial para a vaga', max_digits=15)),
                ('disponibilidade_inicio', models.DateField(help_text='Data em que possa ingressar')),
                ('disponibilidade_locomocao', models.BooleanField(help_text='Disponibilidade para mudança de cidade ou estado')),
                ('regime_trabalho', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=50)),
                ('status', models.CharField(choices=[('em_analise', 'Em Analise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='em_analise', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacao_rh', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
