# Generated by Django 6.0.1 on 2026-02-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entre_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='disponibilidade_locomocao',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=30),
        ),
    ]
